
import skchem
from rdkit.Chem.rdMolDescriptors import GetMorganFingerprintAsBitVect as morg
from synergy_maps import *
from sklearn.decomposition import PCA
from sklearn.manifold import MDS
import sys


def make_map():

    sys.stdout.write('Making representations:')

    sys.stdout.write(' [ ')
    sys.stdout.write('random')
    random = RepresentationType(name='random',
        representation_func=lambda m: pd.Series(np.random.random(100)),
        metadata="""Uniformly distributed between 0 and 1 random feature vector, """ 
        """implemented using numpy random module""")
    sys.stdout.write(', morg2')
    morg2 = RepresentationType(name='morg2', 
        representation_func=skchem.skchemize(morg, radius=2, nBits=2048),
        metadata="""Hashed Circular fingerprint generated by the Morgan algorithm, """
            """implemented in RDKit. """
            """Radius = 2, Bit length = 2048""")

    sys.stdout.write(' ] ')

    representation_types = [ random, morg2 ]

    sys.stdout.write('...OK\n')
    # reduction methods    

    sys.stdout.write('Making reduction methods: ')

    sys.stdout.write(' [ ')

    sys.stdout.write('PCA')
    pca = ReductionMethod(name='PCA',  
        model=PCA(n_components=2), 
        metadata="""Principal component analysis implemented in scikit-learn""")

    sys.stdout.write(', MDS')

    mds = ReductionMethod(name='MDS',
        model=MDS(),
        metadata=
            """MultiDimensional Scaling implemented in scikit-learn""")

    sys.stdout.write(', TSNE')

    tsne = ReductionMethod(name='t-SNE',
        model=TSNE(perplexity=1),
        metadata=
            """Student's t-distributed stochastic neighbour embedding, """
            """implemented according to van der Maartin et al. 2014"""
            """Perplexity = 1, theta=0""")

    sys.stdout.write(' ] ')

    reduction_methods = [ pca, mds, tsne ]

    sys.stdout.write('...OK\n')

    # activity types
    sys.stdout.write('Making Activity Types:')

    sys.stdout.write(' [ ')

    sys.stdout.write('pIC20')
    pIC20 = ActivityType(name='pIC20', metadata=
        """negative based-10 logarithm of the IC20, the concentation of"""
        """compound required for 20% inhibition of growth of Lymphoma cells""")

    sys.stdout.write(' ] ')

    activity_types = [ pIC20 ]

    sys.stdout.write('...OK\n')

    # synergy types
    sys.stdout.write('Making Synergy Types:')

    sys.stdout.write(' [ ')

    sys.stdout.write('Excess Over Bliss')
    excessOverBliss = SynergyType(name='Excess over Bliss', metadata=
        """Difference in observed vs expected activity of the component compounds,"""
        """each at the IC20 concentration (when known) assuming the Bliss Independence model""")

    sys.stdout.write(' ] ')

    synergy_types = [ excessOverBliss ]

    sys.stdout.write('...OK\n')

    # data
    sys.stdout.write('Reading in compounds:')
    compound_df = skchem.read_smiles('/Users/RichLewis/Git/Synergy-Maps/backend/synergy_maps/examples/DREAM_Lymphoma/compounds.smiles')
    compound_df.set_index('id', inplace=True)
    sys.stdout.write('...OK\n')

    sys.stdout.write('Reading in combinations:')
    combination_df = pd.read_csv('/Users/RichLewis/Git/Synergy-Maps/backend/synergy_maps/examples/DREAM_Lymphoma/combinations.csv')
    combination_df.set_index('id', inplace=True)
    sys.stdout.write('...OK\n')

    sm = SynergyMap(compound_df=compound_df,
        combination_df=combination_df,
        representation_types=representation_types,
        reduction_methods=reduction_methods,
        activity_types=activity_types,
        synergy_types=synergy_types)

    return sm

if __name__ == "__main__":
    sm = make_map()
    #sys.stdout.write(sm.to_json())



